name: CI/CD

'on':
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION }}
  IMAGE: asia.gcr.io/${{ secrets.PROJECT_ID }}/renderer:${{ github.sha }}

jobs:
  delivery:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.NEW_GCP_SERVICE_ACCOUNT_KEY_BASE64 }}'

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker

      - name: Build a docker image
        run: docker build -t ${{ env.IMAGE }} .

      - name: Push the docker image
        run: docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        run: | 
          gcloud run deploy renderer \
            --project=$PROJECT_ID \
            --image=$IMAGE \
            --region=$REGION \
            --platform managed \
            --allow-unauthenticated

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LIVENOTE_11939 }}'
          channelId: live
          projectId: ${{ secrets.PROJECT_ID }}

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: 'livenote-function'
          runtime: 'nodejs16'